### ISSUE TITLE
Refactoring of field "$teamName" of Class "team" 

### ISSUE THREAD

**Issue by SherwoodCH** [WP-SUHV/wp-suapi#2]
Depending on which API one uses, the name of a team is different:

* Getting the team name via TeamList-API gives something as "Herren NLA Gruppe 1". 
* Getting the team name via TeamDetails-API gives something as "UHC Uster II". 

The second value is the unique name of a team whereas the first one is more the description of the league. For the moment I added the second value as additional field "$teamTitle" in the class "team". But I think this should be cleaned and refactored.

**Comment by SherwoodCH** [comment]
ok in the end I think its ok when we use the team name from TeamDetails-API as "$teamTitle"

**Comment by meip** [comment]
This is one of the thousands big issues I had with the new API of swiss unihockey and it's inconsistencies. The API isn't a data supplier it's furthermore a view renderer :(
